### ISSUE TITLE
iOS: active moment screen status bar showing

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#24]
**Describe the bug**
The status bar should not be shown on the active moment screen. This is now the case for all moments.
![2018-11-12 17 33 59](https://user-images.githubusercontent.com/18073152/48361542-06531a00-e6a2-11e8-947b-b781aa966bcf.png)

**Comment by ConradoMateu** [comment]
with hedvig's iphone for me I fixed it but the problem is that the close button is a little bit overlapping the progressbar

**Comment by mawlle** [comment]
Seem to work on iOS 10.xx but no 11.xx or 12.xx

**Comment by mawlle** [comment]
This issue remains in version 2.1.8 StagecastDEV.
I'm using iPhone 6 iOS 11.2.1

**Comment by mawlle** [comment]
Closing issue as it's not worth spend more time on atm
